### ISSUE TITLE
Testing checklist and feedback for 0.9.0

### ISSUE THREAD

**Issue by frasertweedale** [willdonnelly/dyre#39]
This issue is a place to leave feedback when testing the 0.9.0 release.  Any general feedback, including *"I tested X on platform Y and it worked"* can go here.  Problem reports can go here to (I will clone to separate tickets as appropriate).

Release candidate is available from https://hackage.haskell.org/package/dyre-0.9.0/candidate, or just clone this repo and check out the [dyre-0.9.0-rc1](https://github.com/willdonnelly/dyre/releases/tag/dyre-0.9.0-rc1) tag.

Things that need to be tested:

- [ ] Stack support
- [ ] Cabal store support (something in test suite or CI would be good)
- [x] Windows
- [x] OS X
- [x] FreeBSD
- [ ] GHC 7.10 (omitted from CI for technical reasons)
- [x] GHC 9.0 (omitted from CI because not yet in PPA)

**Comment by frasertweedale** [comment]
Test suite passes on FreeBSD.

**Comment by frasertweedale** [comment]
Test suite passes on Mac OS X + GHC 9.0.1: https://github.com/willdonnelly/dyre/runs/1919074924

**Comment by frasertweedale** [comment]
Test suite passes on Windows + GHC 9.0.1: https://github.com/willdonnelly/dyre/runs/1927011404?check_suite_focus=true

**Comment by frasertweedale** [comment]
Haskell-CI matrix now includes GHC 9.0.1 (using head.hackage): https://github.com/willdonnelly/dyre/runs/2109966510 .

**Comment by frasertweedale** [comment]
Released: https://hackage.haskell.org/package/dyre-0.9.0 .
